services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    PhpCommon\Security\JwtService:
        arguments:
            $secret: '%env(JWT_SECRET)%'

    redis.connection:
        class: Redis
        calls:
            - [connect, ['%env(REDIS_HOST)%', 6379]]

    PhpCommon\Security\TokenBlacklistService:
        arguments:
            $redis: '@redis.connection'

    App\EventSubscriber\JwtAuthSubscriber:
        arguments:
            $jwtService: '@PhpCommon\Security\JwtService'
            $blacklistService: '@PhpCommon\Security\TokenBlacklistService'
        tags:
            - { name: kernel.event_subscriber }
