services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    PhpCommon\Security\JwtService:
        arguments:
            $secret: '%env(JWT_SECRET)%'

    App\EventSubscriber\JwtAuthSubscriber:
        arguments:
            $jwtService: '@PhpCommon\Security\JwtService'
        tags:
            - { name: kernel.event_subscriber }

    App\Service\ProxyService:
        arguments:
            $routeMap:
                '/user':        'http://user-service'
                '/account':     'http://account-service'
                '/transaction': 'http://transaction-service'
                '/ledger':      'http://ledger-service'
